[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = 'probe-rs run --chip STM32F072RBTx'
rustflags = [
    # Linker script from cortex-m-rt
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
    # Enable defmt.
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"
